package com.apps.mycontactsapp.service.impl;

import com.apps.mycontactsapp.exceptions.ValidationException;
import com.apps.mycontactsapp.model.User;
import com.apps.mycontactsapp.model.UserType;
import com.apps.mycontactsapp.repository.UserRepository;
import com.apps.mycontactsapp.service.UserFactory;
import com.apps.mycontactsapp.service.UserService;

/**
 * Implementation of the {@link UserService} interface.
 * <p>
 * This service handles the core business logic for user registration, including
 * input validation,
 * user type handling, and persistence coordination.
 */
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;

    /**
     * Constructs a new UserServiceImpl with the required repository dependency.
     * <p>
     * This constructor supports Dependency Injection (DI) as per the Inversion of
     * Control (IoC) principle.
     *
     * @param userRepository the repository for user data persistence.
     */
    public UserServiceImpl(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    /**
     * Registers a new user based on the provided details.
     * <p>
     * <b>Design Patterns:</b>
     * <ul>
     * <li><b>Factory Pattern:</b> Uses {@link UserFactory} for creating concrete
     * {@link User} instances
     * (e.g., FreeUser, PremiumUser) based on the {@code userType} string.
     * This encapsulates the object creation logic and promotes loose coupling.</li>
     * <li><b>Builder Pattern:</b> The {@link UserFactory} internally uses the
     * Builder Pattern (via {@code User.UserBuilder})
     * to construct complex user objects step-by-step, ensuring mandatory fields are
     * set and validation rules are applied.</li>
     * </ul>
     *
     * @param name        the name of the user.
     * @param email       the email address (must be unique).
     * @param password    the password (will be validated and hashed).
     * @param userTypeStr the string representation of the {@link UserType} (e.g.,
     *                    "FREE", "PREMIUM").
     * @throws ValidationException if the email already exists, the user type is
     *                             invalid, or password validation fails.
     */
    @Override
    public void registerUser(String name, String email, String password, String userTypeStr)
            throws ValidationException {
        // 1. Check if user already exists
        if (userRepository.existsByEmail(email)) {
            throw new ValidationException("User with email " + email + " already exists");
        }

        // 2. Parse UserType
        UserType userType;
        try {
            userType = UserType.valueOf(userTypeStr.toUpperCase());
        } catch (IllegalArgumentException | NullPointerException e) {
            throw new ValidationException("Invalid user type: " + userTypeStr);
        }

        // 3. Create User using Factory
        // Note: ID is null for new user, to be generated by repository/DB
        User newUser = UserFactory.createUser(userType, null, name, email, password);

        // 4. Save User
        userRepository.save(newUser);
    }
}
