package com.apps.mycontactsapp.repository.stub;

import java.util.HashMap;
import java.util.Map;

import com.apps.mycontactsapp.model.User;
import com.apps.mycontactsapp.repository.UserRepository;

public class UserRepositoryStub implements UserRepository {
    private final Map<String, User> users = new HashMap<>();
    private long idCounter = 1;

    @Override
    public User save(User user) {
        // Simulate saving to DB (generating ID)
        // In a real app, we'd probably use a clone or reflection to set the ID if it's
        // not set
        // For this stub, we just store it.
        // NOTE: The User object is immutable and ID is final.
        // In a real scenario, the Repository might return a NEW User object with the ID
        // set.
        // However, our UserBuilder allows setting ID.
        // Let's cheat a bit for the stub and just print it, or assume the
        // Factory/Service should have handled ID generation if it was UUID.
        // Since ID is Long and generated by DB, we can't easily set it on the
        // *existing* immutable User object.
        // We would effectively need to rebuild it.

        System.out.println("STUB: Saving user " + user.getName() + " (" + user.getEmail() + ")");
        users.put(user.getEmail(), user);
        return user;
    }

    @Override
    public java.util.Optional<com.apps.mycontactsapp.model.User> findByEmail(String email) {
        return java.util.Optional.ofNullable(users.get(email));
    }

    @Override
    public boolean existsByEmail(String email) {
        return users.containsKey(email);
    }

}
